import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { cookies } from 'next/headers';

export async function createClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing Supabase environment variables');
  }

  const cookieStore = await cookies();

  return createServerClient(
    supabaseUrl,
    supabaseKey,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch {
            // Handle cookies in Server Components
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options });
          } catch {
            // Handle cookies in Server Components
          }
        },
      },
    }
  );
}

export async function createAdminClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing Supabase environment variables');
  }

  const cookieStore = await cookies();

  return createServerClient(
    supabaseUrl,
    supabaseKey,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch {
            // Handle cookies in Server Components
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options });
          } catch {
            // Handle cookies in Server Components
          }
        },
      },
    }
  );
}

export async function getCurrentUser() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) return null;

    const { data: profile, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', user.id)
      .single();

    // If profile doesn't exist, create it
    if (error || !profile) {
      const { data: newProfile } = await supabase
        .from('profiles')
        .upsert({
          id: user.id,
          email: user.email,
          full_name: user.user_metadata?.full_name || user.email?.split('@')[0] || 'User',
        })
        .select()
        .single();

      return newProfile || {
        id: user.id,
        email: user.email,
        full_name: user.user_metadata?.full_name || 'User',
        tier: null,
      };
    }

    return profile;
  } catch (error) {
    console.error('Error getting current user:', error);
    return null;
  }
}

export async function checkIsAdmin(userId: string): Promise<boolean> {
  const supabase = await createClient();
  const { data: profile } = await supabase
    .from('profiles')
    .select('email')
    .eq('id', userId)
    .single();

  if (!profile) return false;

  const adminEmails = (process.env.ADMIN_EMAILS || '').split(',').map((e) => e.trim().toLowerCase());
  return adminEmails.includes(profile.email.toLowerCase());
}

export async function getPromoCode(): Promise<string> {
  const supabase = await createClient();
  const { data } = await supabase
    .from('admin_settings')
    .select('value')
    .eq('key', 'promo_code_1xbet')
    .single();

  return data?.value || process.env.NEXT_PUBLIC_1XBET_PROMO_CODE || 'ALGOPRONO2025';
}

export interface UserStats {
  combinesGenerated: number;
  successRate: number;
  totalWinnings: number;
  streak: number;
}

export async function getUserStats(userId: string): Promise<UserStats> {
  const supabase = await createClient();

  // Get total combines generated by user
  const { count: combinesCount } = await supabase
    .from('combine_usage_log')
    .select('*', { count: 'exact', head: true })
    .eq('user_id', userId);

  // For now, return real count with placeholder success rate
  // In production, you'd track wins/losses in a separate table
  return {
    combinesGenerated: combinesCount || 0,
    successRate: 0, // Will be calculated when results are tracked
    totalWinnings: 0, // Will be calculated when bets are tracked
    streak: 0, // Will be calculated when results are tracked
  };
}

export interface RecentCombine {
  id: string;
  matches: unknown[];
  totalOdds: number;
  createdAt: string;
  status: 'pending' | 'won' | 'lost';
}

export async function getUserRecentCombines(userId: string, limit = 5): Promise<RecentCombine[]> {
  const supabase = await createClient();

  const { data: usageLogs } = await supabase
    .from('combine_usage_log')
    .select(`
      id,
      created_at,
      combine_id,
      generated_combines (
        id,
        matches,
        total_odds,
        created_at
      )
    `)
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (!usageLogs || usageLogs.length === 0) {
    return [];
  }

  return usageLogs.map((log) => {
    const combine = log.generated_combines as {
      id: string;
      matches: unknown[];
      total_odds: number;
      created_at: string;
    } | null;

    return {
      id: combine?.id || log.id,
      matches: (combine?.matches as unknown[]) || [],
      totalOdds: combine?.total_odds || 0,
      createdAt: log.created_at,
      status: 'pending' as const, // Status tracking would be added later
    };
  });
}

export async function getVipVerificationStatus(userId: string): Promise<{
  status: 'none' | 'pending' | 'approved' | 'rejected';
  submittedAt?: string;
}> {
  const supabase = await createClient();

  const { data: verification } = await supabase
    .from('vip_verifications')
    .select('status, created_at')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (!verification) {
    return { status: 'none' };
  }

  return {
    status: verification.status as 'pending' | 'approved' | 'rejected',
    submittedAt: verification.created_at,
  };
}
